# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: lib/ckb/core.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "Recipient" do
    optional :module, :uint32, 1
    optional :lock, :bytes, 2
  end
  add_message "OutPoint" do
    optional :hash, :bytes, 1
    optional :index, :uint32, 2
  end
  add_message "CellInput" do
    optional :previous_output, :message, 1, "OutPoint"
    optional :unlock, :bytes, 2
  end
  add_message "CellOutput" do
    optional :module, :uint32, 1
    optional :capacity, :uint32, 2
    optional :data, :bytes, 3
    optional :lock, :bytes, 4
    optional :recipient, :message, 5, "Recipient"
  end
  add_message "OperationGrouping" do
    optional :transform_count, :uint32, 1
    optional :destroy_count, :uint32, 2
    optional :create_count, :uint32, 3
  end
  add_message "Transaction" do
    optional :version, :uint32, 1
    repeated :deps, :message, 2, "OutPoint"
    repeated :inputs, :message, 3, "CellInput"
    repeated :outputs, :message, 4, "CellOutput"
  end
  add_message "Header" do
    optional :version, :uint32, 1
    optional :parent_hash, :bytes, 2
    optional :timestamp, :uint64, 3
    optional :height, :uint64, 4
    optional :transactions_root, :bytes, 5
    optional :difficulty, :bytes, 6
    optional :nonce, :uint64, 7
    optional :mix_hash, :bytes, 8
  end
  add_message "Block" do
    optional :block_header, :message, 1, "Header"
    repeated :transactions, :message, 2, "Transaction"
  end
end

Recipient = Google::Protobuf::DescriptorPool.generated_pool.lookup("Recipient").msgclass
OutPoint = Google::Protobuf::DescriptorPool.generated_pool.lookup("OutPoint").msgclass
CellInput = Google::Protobuf::DescriptorPool.generated_pool.lookup("CellInput").msgclass
CellOutput = Google::Protobuf::DescriptorPool.generated_pool.lookup("CellOutput").msgclass
OperationGrouping = Google::Protobuf::DescriptorPool.generated_pool.lookup("OperationGrouping").msgclass
Transaction = Google::Protobuf::DescriptorPool.generated_pool.lookup("Transaction").msgclass
Header = Google::Protobuf::DescriptorPool.generated_pool.lookup("Header").msgclass
Block = Google::Protobuf::DescriptorPool.generated_pool.lookup("Block").msgclass
