# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: lib/ckb/adt/adt.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "CKB.ADT.ValueNode" do
    repeated :value, :bytes, 1
  end
end

module CKB
  module ADT
    ValueNode = Google::Protobuf::DescriptorPool.generated_pool.lookup("CKB.ADT.ValueNode").msgclass
  end
end
