# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: lib/ckb/adt/mpt.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "CKB.ADT.MPTNode" do
    repeated :values, :bytes, 1
  end
end

module CKB
  module ADT
    MPTNode = Google::Protobuf::DescriptorPool.generated_pool.lookup("CKB.ADT.MPTNode").msgclass
  end
end
