# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: lib/ckb/mpt/mpt.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "CKB.MPTNode" do
    repeated :values, :bytes, 1
  end
end

module CKB
  MPTNode = Google::Protobuf::DescriptorPool.generated_pool.lookup("CKB.MPTNode").msgclass
end
